spring:
  application:
    name: API-GATEWAY

server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      prefer-ip-address: true

zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    user-service:
      path: /user/**
      serviceId: USER-SERVICE
      strip-prefix: false
    product-service:
      path: /product/**
      serviceId: PRODUCT-SERVICE
      strip-prefix: false
  host:
    socket-timeout-millis: 30000
