INSERT INTO USERS (ID, NAME) VALUES (1, 'Fabio');
INSERT INTO USERS (ID, NAME) VALUES (2, 'Rafael');
INSERT INTO USERS (ID, NAME) VALUES (3, 'Lucas');
INSERT INTO USERS (ID, NAME) VALUES (4, 'Giliardi');
INSERT INTO USERS (ID, NAME) VALUES (5, 'Guilherme');