INSERT INTO PRODUCTS (ID, NAME, USER_ID) VALUES (1, 'Colher', 1);
INSERT INTO PRODUCTS (ID, NAME, USER_ID) VALUES (2, 'Faca', 1);
INSERT INTO PRODUCTS (ID, NAME, USER_ID) VALUES (3, 'Garfo', 2);
INSERT INTO PRODUCTS (ID, NAME, USER_ID) VALUES (4, 'Lapis', 2);
INSERT INTO PRODUCTS (ID, NAME, USER_ID) VALUES (5, 'Caneta', 3);
INSERT INTO PRODUCTS (ID, NAME, USER_ID) VALUES (6, 'Borracha', 3);
